#!/bin/bash

if [ "$1" == "start" ] || [ "$1" == "run" ]; then
   jupyter notebook

elif [ "$1" == "convert" ] || [ "$1" == "html" ]; then
   for ipynb in *.ipynb; do
      jupyter nbconvert --to html "$ipynb"
   done;

else
   echo "Command '$1' unknown. Please enter a valid command"
fi